import React from 'react';
import { Audio, Sequence, staticFile } from 'remotion';
import { mixer, musicBed, sfxCues } from '../../audio/manifest';
import { scenes, sceneStarts, voiceLeadInFrames } from '../../film/contentFusionFilm';
import { voiceManifest } from '../../film/voiceManifest';

/**
 * Timeline audio.
 *
 * Narration is placed per scene at the scene start + lead-in, using the file
 * generated by `npm run voice`. When no narration has been generated the
 * component renders nothing, so the picture still previews cleanly.
 *
 * Music/SFX are wired but reference placeholder files; `enableSfx` stays off
 * until real assets land (missing files would fail the render).
 */
export const FilmAudio: React.FC<{
  enableVoice?: boolean;
  enableMusic?: boolean;
  enableSfx?: boolean;
}> = ({ enableVoice = true, enableMusic = false, enableSfx = false }) => (
  <>
    {enableVoice && voiceManifest.status === 'generated'
      ? scenes.map((scene, i) => {
          if (!scene.narrationId) return null;
          const entry = voiceManifest.entries[scene.narrationId];
          if (!entry) return null;
          return (
            <Sequence
              key={scene.id}
              from={(sceneStarts[i] ?? 0) + voiceLeadInFrames}
              durationInFrames={scene.durationInFrames}
              name={`voice:${scene.id}`}
            >
              <Audio src={staticFile(entry.file)} volume={mixer.voice.gain} />
            </Sequence>
          );
        })
      : null}

    {enableMusic ? <Audio src={staticFile(musicBed.file)} volume={mixer.music.gain} /> : null}

    {enableSfx
      ? scenes.flatMap((scene, i) =>
          scene.sfx.map((cueId) => {
            const cue = sfxCues[cueId];
            if (!cue) return null;
            return (
              <Sequence
                key={`${scene.id}-${cueId}`}
                from={sceneStarts[i] ?? 0}
                durationInFrames={scene.durationInFrames}
                name={`sfx:${scene.id}:${cueId}`}
              >
                <Audio src={staticFile(cue.file)} volume={mixer[cue.layer].gain * cue.gain} />
              </Sequence>
            );
          }),
        )
      : null}
  </>
);
