#!/usr/bin/env bash
# fop.sh — Reproduce the "Format PDF" step from the DITA-OT build.
#
# Runs Apache FOP directly on the pre-generated XSL-FO file (topic.fo),
# bypassing all DITA preprocessing, and times the rendering.
#
# Prerequisites:
#   - DITA-OT 4.3.1 installed (for FOP jars and fop.xconf)
#   - topic.fo present (generated by dita-ot-fo-only.sh or a full build
#     run with -Dclean.temp=no)
#
# Usage:
#   bash fop.sh
#   FO_FILE=/path/to/topic.fo DITA_OT=/path/to/dita-ot-4.3.1 bash fop.sh

set -euo pipefail

WORKDIR="${WORKDIR:-/tmp/oxygen-chemistry-pdf}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FO_FILE="${FO_FILE:-${SCRIPT_DIR}/topic.fo}"
DITA_OT="${DITA_OT:-${WORKDIR}/dita-ot-4.3.1}"
OUT_PDF="${OUT_PDF:-${WORKDIR}/output-fop-standalone/UserManual.pdf}"
FOP_XCONF="${FOP_XCONF:-${DITA_OT}/plugins/org.dita.pdf2.fop/cfg/fop.xconf}"

log() { printf '[fop] %s\n' "$*" >&2; }

if [ ! -f "$FO_FILE" ]; then
  log "ERROR: FO file not found: $FO_FILE"
  log "Generate it first:"
  log "  bash dita-ot-fo-only.sh   # runs DITA-OT with -Dclean.temp=no and copies topic.fo"
  exit 1
fi

if [ ! -d "$DITA_OT" ]; then
  log "ERROR: DITA-OT not found at $DITA_OT"
  log "Set DITA_OT=/path/to/dita-ot-4.3.1 or run from the project workdir"
  exit 1
fi

mkdir -p "$(dirname "$OUT_PDF")"

FOP_LIB="${DITA_OT}/plugins/org.dita.pdf2.fop/lib"

FO_SIZE=$(du -sh "$FO_FILE" | cut -f1)
log "FO file    : $FO_FILE ($FO_SIZE)"
log "Output PDF : $OUT_PDF"
log "FOP config : $FOP_XCONF"

# ── Run FOP via the Ant task (same mechanism DITA-OT uses in build_fop.xml) ──
# org.apache.fop.cli.Main uses dynamic classloading that fails outside FOP's
# standard distribution layout; the Ant task avoids this issue entirely.
T0=$(python3 -c 'import time; print(f"{time.perf_counter():.6f}")')

/usr/bin/time -v "${DITA_OT}/bin/ant" \
  -buildfile "${SCRIPT_DIR}/run_fop.xml" \
  -lib "${FOP_LIB}" \
  "-Dfop.lib=${FOP_LIB}" \
  "-Dfo.file=${FO_FILE}" \
  "-Dout.pdf=${OUT_PDF}" \
  "-Dfop.xconf=${FOP_XCONF}" \
  2>&1

ELAPSED=$(python3 -c "import time; print(f'{time.perf_counter()-float(\"$T0\"):.1f}')")

log "Elapsed : ${ELAPSED}s"

if [ -f "$OUT_PDF" ]; then
  PDF_SIZE=$(du -sh "$OUT_PDF" | cut -f1)
  PAGES=$(python3 -c "
import subprocess, sys
r = subprocess.run(['pdfinfo', sys.argv[1]], capture_output=True, text=True)
for l in r.stdout.splitlines():
    if l.startswith('Pages:'):
        print(l.split()[1])
        break
" "$OUT_PDF" 2>/dev/null || echo "unknown")
  log "Output PDF : $OUT_PDF ($PDF_SIZE, $PAGES pages)"
else
  log "ERROR: PDF not generated"
  exit 1
fi
